### ISSUE TITLE
No open source

### ISSUE THREAD

**Issue by hfiguiere** [jwagner/analog-film-emulator#1]
I know I read the README. But the notion of fair use you talk about is irrelevant. Fair use is a concept that is not available in every jurisdiction - and that is somewhat too broad. Basically you are opening a can of worm of liability by telling people "it is not open source but you can look at it".

I was actually really looking forward to try to see how this could be reused to have this on Firefox OS.

Please, consider either making the source code really open source, or hiding it.

**Comment by jwagner** [comment]
@hfiguiere 
I do fully understand that the legal concept of fair use does not exist in every jurisdiction. In fact I live in one where it doesn't. The exact words I used are

> You are of course free to study the code and takes bits and pieces, **I consider this** fair use.

In other words I'm not going to sue or complain if anyone uses bits of that code. Yes, I do realize that this might absolutely not be enough to satisfy the contributor agreements of some open source project.  This is among the reasons why I also explicitly stated this:

> If you have grander plans for it and the lack of a license prevents you from following up on them feel free to contact me.

This is the part I don't get:

> Please, consider either making the source code really open source, or hiding it.

Why do you ask me to hide my code? Who exactly would benefit of me hiding the source? I put the code up so people can see how things work and learn from it, I don't see how this is a bad thing.

Now regarding reusing the code:
The reusable part is really trivial code, most operations would be one liners in a more terse programming language. Should you want to reuse it I'm happy to stick a more liberal license to that part of the code.

What I want to prevent is that lazy douchebags just copy my work, ruin it in various ways, taint it with ads and then claim it is their own.

**Comment by hfiguiere** [comment]
If you don't want people to reuse your code, then the best is to keep it to yourself - hence my suggestion to hide it. Saying that one can reuse the code but then can't because the circumstances might not please - being unclear is worse than anything else.

There are licenses that would actually require publishing the source code under most circumstance. Plenty to pick from. Most of them are actually open source - few aren't - and are clear to anyone.
