### ISSUE TITLE
Need build instructions

### ISSUE THREAD

**Issue by bibhas2** [jwagner/analog-film-emulator#3]
Hi, great project! But can we please have some instructions on how to build and run this locally. I tried running:

```
npm install
grunt build
```

But got an error message from Grunt:

```
>> Tasks directory "tasks" not found.

Running "browserify:main" (browserify) task
>> Error: Cannot find module './clut.json' from '/Users/bibhas/Downloads/analog-film-emulator/src'
Warning: Error running grunt-browserify. Use --force to continue.

Aborted due to warnings.
```

**Comment by jwagner** [comment]
Hello bibhas2,

Analog-film-emulator is not an open source project. I published the code for other people to understand how it works. Not for others to build on top of it. 

This is of course not final. I'd like to release it under a more permissive license at some point but I haven't figured out any satisfying way of doing that yet. I want to allow others to hack on this and improve it, but I don't want people to just copy it and slam it full of ads.

Anyways we'll see. :)

I'll try to remember to ping you should I release it as a proper open source project.

**Comment by bibhas2** [comment]
Hi, my intention is to convert the code into a desktop app using Electron.
